project:
  type: website
  output-dir: "docs"

website:
  title: "AI Cuba"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - orgs.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
